slug = "void-3"
title = "Void 3"
author = "Stephen"
value = 30
description = """I found this strange [site](http://void3.acmcyber.com:10000) that says it will let
you scream into the void. For some reason the void tends to echo these screams back and they can
sometimes be heard in other places. We can hear them [here](http://admin.acmcyber.com:10000) because we
administer this site. The admin there has some secrets so don't go sneaking around..."""
tags = ["xss"]
files = []
flag = "flag{eric_andre_outside_the_textarea}"
enabled = true
