slug = ""
title = "Email Sanitizer"
author = "Jeffrey"
value = 35
description = """A better, more improved version of [the tool](http://redacter-improved.acmcyber.com:10000) is here. Now with updated [whitelist](cmd_whitelist.txt)"""
tags = ["web"]
files = ["cmd_whitelist.txt"]
flag = "flag{m0n3-ymov-3s}"
enabled = true
