version: "3.9"
services:
    redis:
        image: redis
    level1:
        build: .
        ports:
            - "7008:3000"
        environment:
            - XSS_LEVEL=1
    level2:
        build: .
        ports:
            - "7009:3000"
        environment:
            - XSS_LEVEL=2
    level3:
        build: .
        ports:
            - "7010:3000"
        environment:
            - XSS_LEVEL=3
    level4:
        build: .
        ports:
            - "7011:3000"
        environment:
            - XSS_LEVEL=4
    level5:
        build: .
        ports:
            - "7012:3000"
        environment:
            - XSS_LEVEL=5
