slug = "git-gud"
title = "Git Gud"
author = "defund"
value = 20
description = "I made a personal [website](gitgud.acmcyber.com:10000)! Not only that, it's backed with source control."
tags = ["intro"]
files = []
flag = "flag{lets_git_it}"
enabled = true
