slug = "notepad-2"
title = "Notepad 2.0"
author = "Stephen"
value = 20
description = """Looks like some people's notes were collecting/sending user data. Not good!

You can post (almost) anything [here](http://blogpost1.acmcyber.com:10000), and it saves to a unique url! Send your notes url to [the site admin](http://acmcyber.com:10001) if you want us to read them.

Note: the flag is in the admin's cookies."""
tags = ["xss"]
files = []
flag = "flag{character_&#101ncoding_ftw}"
enabled = true
