slug = "notepad-3"
title = "Notepad 3.0"
author = "Stephen"
value = 30
description = """This update is just for fun. Not as easy as it may look, but certainly breakable. (check the headers).

You can post anything [here](http://blogpost1.acmcyber.com:10000), and it saves to a unique url! Send your notes url to [the site admin](http://acmcyber.com:10001) if you want us to read them.

Note: the flag is in the admin's cookies."""
tags = ["xss"]
files = []
flag = "flag{csp_shenanigan_master}"
enabled = true
